name: Manage product
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run tests
        run: |
          ./test_product.sh
  Package:
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Get version tag
        id: autoTagDryRun
        uses: anothrNick/github-tag-action@1.55.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
          WITH_V: true
          DRY_RUN: true
      - name: Print tag information
        run: |
          echo "The next tag version will be: ${{ steps.autoTagDryRun.outputs.new_tag }}"
          echo "The current tag is: ${{ steps.autoTagDryRun.outputs.tag }}"
      - name: Create archive
        run: |
          tar -czvf product.${{ steps.autoTagDryRun.outputs.new_tag }}.tar.gz product.txt
          echo "Output:"
          ls -l *.gz
      - name: Apply tag
        if: github.ref == 'refs/heads/main'
        id: autoTag
        uses: anothrNick/github-tag-action@1.55.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
          WITH_V: true

